type = "card"
title = "Education"
description = ""

[[items]]
title = "Zhejiang University"
subtitle = "Ph.D. in Electronic Information"
date = "Sept. 2023 – Present"
content = "Advisor: Prof. Yuanchao Shu"
image = "/zju.png"

[[items]]
title = "Hangzhou Dianzi University"
subtitle = "M.Sc. in Cyberspace Security"
date = "Sept. 2020 – June 2023"
content = "Ranking: 2/58 · Advisor: Prof. Yiming Wu, Prof. Ning Zheng, Prof. Ming Xu"
image = "/hdu.png"

[[items]]
title = "NingboTech University"
subtitle = "B.Eng. in Software Engineering"
date = "Sept. 2016 – June 2020"
content = "Ranking: 6/85"
image = "/nit.png"
