type = "card"
title = "Experience"
description = ""

[[items]]
title = "University College London (UCL)"
subtitle = "Visiting PhD Student"
date = "Feb. 2026 – Feb. 2027"
content = "Hosted by Prof. Chris Xiaoxuan Lu"
image = "/ucl.png"
