[[news]]
date = "2026-06"
content = "one paper accepted to ACM Transactions on Intelligent Systems and Technology (ACM TIST)! 🎉"

[[news]]
date = "2026-05"
content = "one paper accepted to ACL 2026 (Main)! 🎉"

[[news]]
date = "2025-08"
content = "one paper published in arXiv. 🎉"

[[news]]
date = "2024-10"
content = "one paper accepted to IEEE Transactions on Neural Networks and Learning Systems (IEEE TNNLS)! 🎉"
